{
    "errors": [
        {
            "line": 75,
            "column": 39,
            "stop_line": 75,
            "stop_column": 82,
            "path": "/home/wonseok/benchmark/Zappa-388/zappa/handler.py",
            "code": 19,
            "name": "Too many arguments",
            "description": "Too many arguments [19]: Call `object.__new__` expects 1 positional argument, 3 were provided.",
            "long_description": "Too many arguments [19]: Call `object.__new__` expects 1 positional argument, 3 were provided.",
            "concise_description": "Too many arguments [19]: Expected 1 positional argument.",
            "define": "zappa.handler.LambdaHandler.__new__",
            "scenarios": ""
        },
        {
            "line": 348,
            "column": 61,
            "stop_line": 348,
            "stop_column": 68,
            "path": "/home/wonseok/benchmark/Zappa-388/zappa/handler.py",
            "code": 70,
            "name": "Undefined attribute with reference",
            "description": "Undefined attribute with reference [70]: `None` has no attribute `__getitem__`.",
            "long_description": "Undefined attribute with reference [70]: `None` has no attribute `__getitem__`.",
            "concise_description": "Undefined attribute with reference [70]: `None` has no attribute `__getitem__`.",
            "define": "zappa.handler.LambdaHandler.handler",
            "scenarios": ""
        },
        {
            "line": 464,
            "column": 67,
            "stop_line": 464,
            "stop_column": 77,
            "path": "/home/wonseok/benchmark/Zappa-388/zappa/handler.py",
            "code": 70,
            "name": "Undefined attribute with reference",
            "description": "Undefined attribute with reference [70]: `NameError` has no attribute `message`.",
            "long_description": "Undefined attribute with reference [70]: `NameError` has no attribute `message`.\n`NameError` is defined in a stub file at `builtins.pyi`. Ensure attribute `message` is defined in the stub file.",
            "concise_description": "Undefined attribute with reference [70]: `NameError` has no attribute `message`.",
            "define": "zappa.handler.LambdaHandler.handler",
            "scenarios": ""
        },
        {
            "line": 471,
            "column": 64,
            "stop_line": 471,
            "stop_column": 72,
            "path": "/home/wonseok/benchmark/Zappa-388/zappa/handler.py",
            "code": 71,
            "name": "Incompatible parameter type with reference",
            "description": "Incompatible parameter type with reference [71]: In call `traceback.format_exception`, for 1st positional only parameter expected `Union[None, Type[BaseException], BaseException, bool, int, TracebackType]` but got `Union[None, Type[BaseException], BaseException, TracebackType]`.",
            "long_description": "Incompatible parameter type with reference [71]: In call `traceback.format_exception`, for 1st positional only parameter expected `Union[None, Type[BaseException], BaseException, bool, int, TracebackType]` but got `Union[None, Type[BaseException], BaseException, TracebackType]`.",
            "concise_description": "Incompatible parameter type with reference [71]: For 1st param expected `Union[None, Type[BaseException], BaseException, bool, int, TracebackType]` but got `Union[None, Type[BaseException], BaseException, TracebackType]`.",
            "define": "zappa.handler.LambdaHandler.handler",
            "scenarios": ""
        },
        {
            "line": 183,
            "column": 23,
            "stop_line": 185,
            "stop_column": 66,
            "path": "/home/wonseok/benchmark/Zappa-388/zappa/letsencrypt.py",
            "code": 70,
            "name": "Undefined attribute with reference",
            "description": "Undefined attribute with reference [70]: Optional type has no attribute `groups`.",
            "long_description": "Undefined attribute with reference [70]: Optional type has no attribute `groups`.\n`typing.Optional[typing.Match[str]]` is defined in a stub file at `typing.pyi`. Ensure attribute `groups` is defined in the stub file.",
            "concise_description": "Undefined attribute with reference [70]: Optional type has no attribute `groups`.",
            "define": "zappa.letsencrypt.get_boulder_header",
            "scenarios": ""
        },
        {
            "line": 249,
            "column": 37,
            "stop_line": 249,
            "stop_column": 53,
            "path": "/home/wonseok/benchmark/Zappa-388/zappa/letsencrypt.py",
            "code": 71,
            "name": "Incompatible parameter type with reference",
            "description": "Incompatible parameter type with reference [71]: In call `hashlib.sha256`, for 1st positional only parameter expected `Union[array[typing.Any], bytearray, bytes, _CData, memoryview, mmap]` but got `str`.",
            "long_description": "Incompatible parameter type with reference [71]: In call `hashlib.sha256`, for 1st positional only parameter expected `Union[array[typing.Any], bytearray, bytes, _CData, memoryview, mmap]` but got `str`.",
            "concise_description": "Incompatible parameter type with reference [71]: For 1st param expected `Union[array[typing.Any], bytearray, bytes, _CData, memoryview, mmap]` but got `str`.",
            "define": "zappa.letsencrypt.get_cert",
            "scenarios": ""
        },
        {
            "line": 291,
            "column": 16,
            "stop_line": 291,
            "stop_column": 22,
            "path": "/home/wonseok/benchmark/Zappa-388/zappa/letsencrypt.py",
            "code": 70,
            "name": "Undefined attribute with reference",
            "description": "Undefined attribute with reference [70]: `OSError` has no attribute `code`.",
            "long_description": "Undefined attribute with reference [70]: `OSError` has no attribute `code`.\n`OSError` is defined in a stub file at `builtins.pyi`. Ensure attribute `code` is defined in the stub file.",
            "concise_description": "Undefined attribute with reference [70]: `OSError` has no attribute `code`.",
            "define": "zappa.letsencrypt.verify_challenge",
            "scenarios": ""
        },
        {
            "line": 291,
            "column": 35,
            "stop_line": 291,
            "stop_column": 41,
            "path": "/home/wonseok/benchmark/Zappa-388/zappa/letsencrypt.py",
            "code": 70,
            "name": "Undefined attribute with reference",
            "description": "Undefined attribute with reference [70]: `OSError` has no attribute `read`.",
            "long_description": "Undefined attribute with reference [70]: `OSError` has no attribute `read`.\n`OSError` is defined in a stub file at `builtins.pyi`. Ensure attribute `read` is defined in the stub file.",
            "concise_description": "Undefined attribute with reference [70]: `OSError` has no attribute `read`.",
            "define": "zappa.letsencrypt.verify_challenge",
            "scenarios": ""
        },
        {
            "line": 1109,
            "column": 33,
            "stop_line": 1109,
            "stop_column": 37,
            "path": "/home/wonseok/benchmark/Zappa-388/zappa/zappa.py",
            "code": 71,
            "name": "Incompatible parameter type with reference",
            "description": "Incompatible parameter type with reference [71]: In call `sum`, for 1st positional only parameter expected `Iterable[Variable[_SumT (bound to _SupportsSum)]]` but got `Generator[int, None, None]`.",
            "long_description": "Incompatible parameter type with reference [71]: In call `sum`, for 1st positional only parameter expected `Iterable[Variable[_SumT (bound to _SupportsSum)]]` but got `Generator[int, None, None]`.",
            "concise_description": "Incompatible parameter type with reference [71]: For 1st param expected `Iterable[Variable[_SumT (bound to _SupportsSum)]]` but got `Generator[int, None, None]`.",
            "define": "zappa.zappa.Zappa.update_stack",
            "scenarios": ""
        }
    ]
}